const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#7C3AED",
    background: "#F8F5FF",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#EC4899",
    secondaryForeground: "#FFFFFF",
    muted: "#F0EBFF",
    mutedForeground: "#6B6B8A",
    accent: "#F3E8FF",
    accentForeground: "#7C3AED",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#E8E0F5",
    input: "#E8E0F5",
    navBg: "#FFFFFF",
    navBorder: "#F0EBFF",
    navIcon: "#374151",
    navBtnBg: "#F8F5FF",
    inputBg: "#F8F5FF",
    chatUserBubble: "#7C3AED",
    chatBotBubble: "#FFFFFF",
    chatBotText: "#1A1A2E",
    recordingBg: "#F3E8FF",
    recordingBorder: "#C4B5FD",
    recordingText: "#5B21B6",
  },
  dark: {
    text: "#F0EBFF",
    tint: "#A855F7",
    background: "#0D0D1A",
    foreground: "#F0EBFF",
    card: "#16162A",
    cardForeground: "#F0EBFF",
    primary: "#A855F7",
    primaryForeground: "#FFFFFF",
    secondary: "#EC4899",
    secondaryForeground: "#FFFFFF",
    muted: "#1E1A36",
    mutedForeground: "#9090B8",
    accent: "#1A0A2E",
    accentForeground: "#A855F7",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D2550",
    input: "#2D2550",
    navBg: "#16162A",
    navBorder: "#2D2550",
    navIcon: "#C4B5FD",
    navBtnBg: "#0D0D1A",
    inputBg: "#0D0D1A",
    chatUserBubble: "#7C3AED",
    chatBotBubble: "#1E1A36",
    chatBotText: "#F0EBFF",
    recordingBg: "#1A0A2E",
    recordingBorder: "#5B21B6",
    recordingText: "#C4B5FD",
  },
  radius: 12,

  gradientHeader: ["#2D0A6E", "#7C3AED", "#EC4899", "#FF6B00"] as string[],
  gradientDrawer: ["#2D0A6E", "#7C3AED"] as string[],
  gradientProfile: ["#7C3AED", "#EC4899"] as string[],
  gradientAlert: ["#EC4899", "#FF6B00"] as string[],

  orange: "#FF6B00",
  pink: "#EC4899",
  purple: "#7C3AED",
  gold: "#FBBF24",
};

export default colors;
